import type { ConcludeWorktreeRequest, CreateWorktreeRequest, WorktreeActionRequest, WorktreeReview, ValidationCommand, ValidationResult, WorktreeId, WorktreeManager, WorktreeManagerOptions, WorktreeLease, WorktreeOwner, WorktreeRecoveryReport, WorktreeDoctorReport, WorktreeView } from './types.js';
export declare class LocalWorktreeManager implements WorktreeManager {
    private readonly options;
    private readonly git;
    private readonly journal;
    private readonly snapshotter;
    private readonly repositoryMutex;
    private closed;
    private readonly operationTails;
    private barrierTail;
    constructor(options: WorktreeManagerOptions);
    private serialized;
    private serializedBarrier;
    create(request: CreateWorktreeRequest): Promise<WorktreeView>;
    inspect(id: WorktreeId): Promise<WorktreeView>;
    private inspectUnserialized;
    review(id: WorktreeId, maxBytes?: number): Promise<WorktreeReview>;
    validate(id: WorktreeId, commands: readonly ValidationCommand[]): Promise<ValidationResult>;
    acquireLease(id: WorktreeId, owner: WorktreeOwner): Promise<WorktreeLease>;
    releaseLease(id: WorktreeId, leaseId: string): Promise<void>;
    act(request: WorktreeActionRequest): Promise<WorktreeView>;
    conclude(request: ConcludeWorktreeRequest): Promise<WorktreeView>;
    list(): Promise<readonly WorktreeView[]>;
    recover(): Promise<WorktreeRecoveryReport>;
    doctor(): Promise<WorktreeDoctorReport>;
    close(): Promise<void>;
    private projection;
    private snapshotOptions;
    private boundary;
    private recoverOne;
    private finishBranch;
    private finishCommit;
    private finishHandoff;
    private finishMerge;
    private finishPush;
    private finishPullRequest;
    private finishArchive;
    private finishRestore;
    private finishPlannedConclude;
    private removedView;
    private inactiveView;
}
//# sourceMappingURL=manager.d.ts.map